### ISSUE TITLE
Size Mismatch Runtime Error

### ISSUE THREAD

**Issue by Rufaidah44** [mamonraab/Data-efficient-video-transformer#1]
Good Day..

I'm trying to run your code. 
I face this issue when adding the w=wight parameter as the path for the saved wight file

size mismatch for 4.weight: copying a param with shape torch.Size([1024, 10240]) from checkpoint, the shape in current model is torch.Size([1024, 20480]).

but the model works fine when not adding it 

any help please ??

**Comment by mamonraab** [comment]
the wight file is corrupted will update the link  and  get back to you

**Comment by mamonraab** [comment]
solved you can re-download the  wights https://drive.google.com/file/d/1s7Z1c-4zC522BFVM5EiZDMQLe6ZV8QQh/view?usp=sharing

**Comment by Rufaidah44** [comment]
Thanks a lot..
I appreciate your support
